### PR TITLE
Fix Composer branch-alias

### PR DESCRIPTION
**Pull request by guilliamxavier**
better late than never :)

### CODE REVIEW

**Comment by tobias-93** [comment]
Thanks @guilliamxavier

**Comment by stof** [comment]
does not make sense, as this is not in the dev-master branch. The dev-master alias is totally ignored outside the master branch.

**Comment by tobias-93** [comment]
@stof true, though it doesn't cause any harm either

**Comment by stof** [comment]
well, it will cause a conflict on next merge of 1.x into master...

**Comment by tobias-93** [comment]
Yeah, gonna fix that in a minute

**Comment by guilliamxavier** [comment]
@stof Ugh, sorry about that... On the other hand, there will be a conflict anyway after (if) PR 294 is merged (compare https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/263/files and https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/294/files), which is to be resolved simply by keeping the master version on master

**Comment by tobias-93** [comment]
@guilliamxavier @stof I merged 1.x to master and resolved the merge conflicts, so there's no problem.

**Pull request merged**
