### PR TITLE
Fixed issue with creating absolute instead of relative path

### PR DESCRIPTION
**Pull request by dew326**
Fixed issue https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/384

Turns out, the check if the host contains a port cannot be done in one place. Each case has to check port on different base `host` or `this.getHost()`.

### CODE REVIEW

**Comment by dmaicher** [comment]
@dew326 I can confirm that this fixes my issue https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/384.

Thanks a lot for the fast fix :+1: :rocket:

**Comment by dew326** [comment]
Hi @tobias-93, could you take a look?

**Comment by tobias-93** [comment]
Hi @dew326, thanks for the contribution! Hopefully this solves all host+port issues, but if any pops up let me know.

**Comment by Lampelk** [comment]
Has this fixed been released? I am having this issue with v3.1.1...

**Comment by tobias-93** [comment]
Hi @Lampelk,

Sorry you're experiencing issues. This PR has been merged and released a long time ago, so I doubt you have the same issue. Please make a Github issue with a description of your problem so we can have a look.

Regards, Tobias

**Pull request merged**
