### PR TITLE
Fix Deprecated : routing controller with single colon

### PR DESCRIPTION
**Pull request by ricostone**
Added :: instead of : for indexAction controller since it is deprecated from Symfony 4.1

### CODE REVIEW

**Comment by tobias-93** [comment]
See #325, #327, #332 and #335, not the right solution.

**Comment by stof** [comment]
this deprecation has been reverted in Symfony (to be re-added in a future 5.x release), precisely because the migration path for shared bundles was not good otherwise (forcing to drop support for the LTS or to get the deprecation) while the code dealing with in in Symfony was quite simple.

the solution is to upgrade to Symfony 4.1.8

**Comment by ricostone** [comment]
Thanks for the feedback ! Sorry for duplicate PR ...

**Comment by althaus** [comment]
> the solution is to upgrade to Symfony 4.1.8

The deprecation is thrown on the fresh 4.2?

**Pull request closed without merging**
