### PR TITLE
adapt for symfony 4.1 i18n routes

### PR DESCRIPTION
**Pull request by alexanza**
I adapted the code to work with the i18n routes of symfony 4.1, I hope I did it correctly

### CODE REVIEW

**Comment by jsncrdnl** [comment]
+1

**Comment by gobolabs** [comment]
+1

**Comment by tobias-93** [comment]
Looking good to me. Anyone with localized routes already tried this?

**Comment by lordjancso** [comment]
Is this will be merged?

**Comment by tobias-93** [comment]
@lordjansco I asked whether it is working since I have no project using localized routes (yet). Nobody answered so I see no reason to merge right now. In case it is tested and working I will merge it.

**Comment by lordjancso** [comment]
@alexanza Please, pull the newest version to your code, then I will test it.

**Comment by alexanza** [comment]
@lordjancso done ;)

**Comment by lordjancso** [comment]
It is tested and works very well! :+1:

**Comment by wickedOne** [comment]
yes, we've been using this feature branch for a while now in one of our applications and works like a charm!

**Comment by tobias-93** [comment]
Thanks, good work @alexanza!

**Pull request merged**
