### PR TITLE
Add HTTP non standard port support for route with specific host

### PR DESCRIPTION
**Pull request by chandon**
To reproduce the bug before fixing it : 
1) have a server on a non standard port (for example 81 instead of 80)
2) have a route with a specific host parameter in routing.yml

```
route_example:
    path:     /example
    defaults: { _controller: ExampleBundle:Example:index }
    host: test.example.com
```

3) generate a full path route using Symfony

```
$this->generateUrl('route_example', array(), true);
```

Ok, we have http://test.example.com:81/example

4) generate a full path using FOSJsRoutingBundle

We got http://test.example.com/example => the 81 port is missing !
And even if you try to generate a relative path, you'll get a full path because FOSJsRoutingBundle compare the host "test.example.com" with this.getHost() "test.example.com:81", and because it's not equals, it generates a full path... see routing.js line 242 :

```
} else if (host && this.getHost() !== host) {
```

### CODE REVIEW

**Comment by merk** [comment]
You do not need to open pull requests each time you make a change. If you work on a feature branch you can push to the remote branch and the PR updates automatically.

https://help.github.com/articles/using-pull-requests/

**Comment by chandon** [comment]
@merk yes i know but i don't want to push 10 commit corrections for only this little change, 1 is enough. And i don't manage to rebase when it's already pushed on github. Sorry for that

**Comment by merk** [comment]
You need to force push when rebasing *on a feature branch* to github.

**Comment by chandon** [comment]
Is the discussion still open ?

**Comment by willdurand** [comment]
Scheduled for 2.0.0

**Comment by chandon** [comment]
Is there any roadmap somewhere for 2.0.0 ? Thx

**Comment by merk** [comment]
The milestone will list what @willdurand has scheduled for 2.0.0: https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/milestones/2.0.0

**Comment by willdurand** [comment]
Yes and I will try to finish the work started a while ago.

**Comment by raziel057** [comment]
+1 for this one. Very useful when working with Vagrant environments.

**Comment by luishdez** [comment]
+1 Very important for dev envs. May be move it to a minor release and merge ? that will be nice

**Comment by chandon** [comment]
@willdurand I don't know if you had time to work on 2.0.0, but this PR is a quite simple change, no BC, travis tests are green, why not to merge it in the current branch ?
We really need it for dev environments

**Comment by sdieunidou** [comment]
+1 with luishdez
can you merge this PR on 1.x branch ?

**Comment by MvanRietschoten** [comment]
+1

**Comment by MvanRietschoten** [comment]
I tried this PR but this doesn't work with the dump command. As it uses the port from the request context object which is always 80 by default... So this implementation will not work for more people I guess... Therefore I created a simple javascript file and changed all Routing.generate() to RoutingManager.generate().

For people with the same problem, here is my RoutingManager.js:

```js
function RoutingManager() {}

/**
 * @param {String} name
 * @param {RouteParams} parameters
 */
RoutingManager.generate = function (name, parameters) {
    var baseRoute = Routing.generate(name, parameters);
    
    if (window.location.port != "80" && window.location.port != "443") {
        return this._addPortToUrl(baseRoute);
    }

    return baseRoute;
};

/**
 * @param {String} baseRoute
 * @returns {String}
 * @private
 */
RoutingManager._addPortToUrl = function (baseRoute) {
    var a = document.createElement('a');
    a.href = baseRoute;
    a.port = window.location.port;

    return a.href;
};
```

**Comment by chandon** [comment]
@MvanRietschoten strange, i'm using it with the dump command, and 

    <script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>

and it returns a result with the non-standard port in  "portextension": ":XXX". So it works well (but i didn't commit any change on my PR since 26 jan. 2015...)

Did you configure the router standard ports ? with Symfony :

    framework:
        router:
            http_port: %http_port%
            https_port: %https_port%

**Comment by MvanRietschoten** [comment]
Ah that would be my problem. I'm including the js directly and didn't configure the default ports for the dev environment. That should work ^^ thanks.

**Comment by meyerbaptiste** [comment]
@willdurand @lsmith77, can you merge this PR if everything seems OK for you?
It's an important misfeature today, especially since it blocks the release of the 2.0.0 version (cf. milestone#1).

**Comment by lsmith77** [comment]
I am not really actively maintaining this Bundle .. but the PR needs a rebase.

**Comment by dmaicher** [comment]
We also need this feature as we are running acceptance tests on a non-standard port :+1:

**Comment by meyerbaptiste** [comment]
@chandon, can you rebase your PR?

**Comment by dmaicher** [comment]
@chandon any news?

**Comment by chandon** [comment]
it's not usual to have a 2 years old PR commited...

**Comment by bangpound** [comment]
@chandon Your branch needed to be rebased against master. Does this look correct? https://github.com/R-Shief/FOSJsRoutingBundle/tree/feature/non-standard-port

**Comment by chandon** [comment]
Still not merged ?

**Comment by DerekRoth** [comment]
Maybe you should add some JS unit tests to show what has been fixed ?

**Comment by bangpound** [comment]
It was accepted by @willdurand almost a year ago but needed a rebase. I have rebased it, but @chandon opened the PR. Now @DerekRoth is asking for tests. Can someone give us clear direction on what it takes to get this merged?

**Comment by DerekRoth** [comment]
I'm not a maintainer of this package, so i'm not "asking" for tests. I just suppose that it would help accepting the merge. I'm glad to help on this if needed.

**Comment by chandon** [comment]
I think i'll delete this PR next week...

**Comment by DerekRoth** [comment]
It would be a shame to keep such an important bug in the bundle... having an API virtual host and a non standard port for dev environment is quite common nowadays. I don't get what is blocking this PR for merging.

**Comment by yellow1912** [comment]
@chandon It's a shame to delete such important PR

@willdurand can you please take a look at it and let us know the state of it please?

**Comment by norbert-yoimo** [comment]
@willdurand ping

**Comment by khrizt** [comment]
So OP closed the PR waiting to death to be merged, that means no intention of fixing this bug?

**Comment by jewome62** [comment]
@willdurand Can we know what is missing for merge this PR ?
Actually we override repository to point on @chandon fork.

(And that work well)

**Pull request closed without merging**
