### PR TITLE
Fix for new way of handling scheme in Symfony 3.0 (1.x)

### PR DESCRIPTION
**Pull request by tobias-93**
Adapt the fix of #254 for version 1.x of the bundle

### CODE REVIEW

**Comment by GuilhemN** [comment]
Can you rebase your branch please? I fixed the tests meanwhile.

**Comment by tobias-93** [comment]
@GuilhemN done

**Comment by GuilhemN** [comment]
thank you @tobias-93!

**Comment by GuilhemN** [comment]
see https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/releases/tag/1.6.1

**Pull request merged**
