### PR TITLE
Allow symfony 7.0

### PR DESCRIPTION
**Pull request by olekans**
- Added Symfony 7 support

### CODE REVIEW

**Comment by tobias-93** [comment]
Hi @olekans, thanks for your contribution! Can you update it so all user Symfony components allow version 7, not just the framework-bundle? Then i can merge this.

**Comment by tobias-93** [comment]
And of course, also update the test definitions so they are also run with SF7 components.

**Comment by olekans** [comment]
Hi @tobias-93, no problem. Done :)

**Comment by tobias-93** [comment]
Hi @olekans, merged. Thanks!

**Pull request merged**
