### PR TITLE
Handling no query string option

### PR DESCRIPTION
**Pull request by lsagetlethias**
Hi,

The main goal of this PR is to prevent non-RESTfull query string in generated url.
- phantomjs test ok
- update doc ok
- update typescript description file ok
- update build.js with plovr ok
- tested in real symfony project
- retrocompatible

### CODE REVIEW

**Comment by willdurand** [comment]
Hi!

> The main goal of this PR is to prevent non-RESTfull query string in generated url.

May I ask you what you mean by "non-RESTfull query string"?

Another question: is there something similar in the Symfony routing lib?

**Comment by Maxooo** [comment]
> May I ask you what you mean by "non-RESTfull query string"?

http://domain.com/user/password/reset/madeleine@shutter.com is restfull
http://domain.com/user/password/reset?mail=madeleine@shutter.com is not restfull

> Another question: is there something similar in the Symfony routing lib?

I don't think there is something similar in the Symfony routing component as it's not only dedicated to a REST usage.

So we would like to remove all extra parameters that are not present in the route pattern instead of generating a URL with "? + &" parameters.

**Comment by willdurand** [comment]
Thanks for your prompt reply. 

I don' think this makes much sense in this bundle to be honest, because this lib is not (only) dedicated to a REST usage either. It tries to match the (PHP) Symfony routing layer, nothing more.

On an unrelated note, having parameters in the query string is perfectly valid in REST. Having a verb part of the URI is more questionable though.

**Comment by cpereirawynd** [comment]
I think it can be really usefull to add this feature to validate all the parameters for RESTfull Query string.
As i see, we only need to add a parameter to validate the query string.
And on top of that, if you don't use GET method you normally don't have query string. 
Actually you have !

**Comment by bios21** [comment]
Hello,

I come again because the actual behavior bugs me out.  
And when I search for any solution on Google, this PR come in 2nd result. 😞 

I don't understand why `Routing.generate()` keeps forcing to put body parameters in a query string.

e.g:
```php
/**
     * @param Request $request
     *
     * @return Response
     *
     * @internal param Request $request
     *
     * @Rest\Post("/call", options = { "expose" = true, "utf-8" = true }, requirements={
     *     "url" = "\/api.*",
     *     "method" = "(GET|POST|PUT|DELETE)+",
     *     "parameters" = "*"
     * }, defaults={"parameters" = "[]"})
     */
    public function callAction(Request $request)
    { /* ... */ }
```

```js
// http://local.dev/app_dev.php/js/routing?callback=fos.Router.setData

/**/fos.Router.setData({
  "base_url": "/app_dev.php",
  "routes": {
    "api_call": {
      "tokens": [
        [
          "text",
          "/api/call"
        ]
      ],
      "defaults": [
        
      ],
      "requirements": {
        "url": "\\/api.*",
        "method": "(GET|POST|PUT|DELETE)+",
        "parameters": "*"
      },
      "hosttokens": [
        
      ]
    },
  "prefix": "",
  "host": "local.dev",
  "scheme": "http"
});
```

But when I call `Routing.generate('api_call', {url: '/api/entities', method: 'GET})` the url generated is `/app_dev.php/api/call?url=%2Fapi%2Fentities&method=GET` AND the `defaults` param in the annotation is ignored...  
I think you need use the `requirements` object to ignore requirements form `unusedParams` array in your `router.js`.

**Pull request closed without merging**
