### PR TITLE
add support for symfony v5

### PR DESCRIPTION
**Pull request by ad3n**
add support for symfony v5

### CODE REVIEW

**Comment by rachel-fizz** [comment]
I think `FOS\JsRoutingBundle\Command\RouterDebugExposedCommand:execute` should return an exit code as seen in the travis jobs and apparently the PHPUnit framework expects return type declarations now.

I would fix these, but I don't think it's possible to add anything to your PR. Really interested in having things up to date with Symfony 5 though :D

**Comment by Cryde** [comment]
It's would be nice to have this bundle in SF5 :pray:

**Comment by kl3sk** [comment]
@rachel-fizz maybe do your own PR ?

**Comment by rachel-fizz** [comment]
> @rachel-fizz maybe do your own PR ?

Sure! I'll take a look later today. Was hoping on @ad3n to make some modifications in the past couple of days :p

**Comment by kl3sk** [comment]
If you know how to, do your own. It will be way faster because of your activity 😉.
And all the community will thank you 👐

**Comment by rachel-fizz** [comment]
To quote my fellow Dutch people: Hoppa!

**Comment by tobias-93** [comment]
Closed in favour of #366

**Pull request closed without merging**
