### PR TITLE
move to psr-4

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A  |
|---          |---|
|Bug Fix?     |n  |
|New Feature? |n  |
|BC Breaks?   |n  |
|Deprecations?|n  |
|Tests Pass?  |n  |
|Fixed Tickets|   |
|License      |MIT|
|Doc PR       |   |

### CODE REVIEW

**Comment by cordoval** [comment]
after merging this would be nice to have a new tag

**Comment by stof** [comment]
Before creating a new tag, the testsuite should be fixed.

The main failure is related to the fact that PHPUnit_MockObject is not able to mock properly a class where a method typehints a non-existent class. This means it is not able to mock the ContainerBuilder anymore when ExpressionLanguage is not available (this is a limitation of PHPUnit_MockObject though. Both Prophecy and Mockery solved this issue)

**Comment by cordoval** [comment]
@stof can we merge this without fixing tests in view that this may take some time?

**Comment by mhor** [comment]
IMO this pull request can be close. Solved in https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/commit/10f11d7c382cbb955cbc7e60e687d59c04e75ece

**Comment by cordoval** [comment]
thanks @mhor :+1: sad that it was not taken in as it was.

**Comment by stof** [comment]
@cordoval I forgot that there was such PR when doing my commit, sorry

**Pull request closed without merging**
