### PR TITLE
Fix URL encoding to mimic Symfony URL Generator

### LINKED ISSUE #385: Some special chars in path must not be percent-encoded
These special chars `/@:;,=+!*|` must not be percent-encoded when they are used in path parameters.

See: https://github.com/symfony/symfony/blob/cd40bb8604ca7842f0ffbaa4ba0782865a976401/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L56-L82

Actually, only `/` char is being restored after being encoded: https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/7dfd2165c1170a73e5929e70fb80ef57f5539869/Resources/js/router.js#L251

### PR DESCRIPTION
**Pull request by ajgarlag**
This PR fixes #385 testing that the generated URL mimic the one generated by Symfony URL Generator.

This PR improves #386

After this PR, spaces in query parameters are encoded as `%20` instead of  `+`

### CODE REVIEW

**Comment by ajgarlag** [comment]
@tobias-93 Friendly ping. Can you review this?

**Comment by tobias-93** [comment]
Hi @ajgarlag, looks good to me! Could you rebase, so I can merge it? Thanks!

**Comment by tobias-93** [comment]
Thanks @ajgarlag

**Comment by ajgarlag** [comment]
Thanks @tobias-93 for merging it

**Pull request merged**
